apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshopper-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eshopper-api
  template:
    metadata:
      labels:
        app: eshopper-api
    spec:
      containers:
      - name: eshopper-api
        image: scwilson1983/eshopper:latest
        ports:
        - containerPort: 443
