apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshopper-db
spec:
  selector:
    matchLabels:
      app: eshopper-db
  template:
    metadata:
      labels:
        app: eshopper-db
    spec:
      containers:
      - name: eshopper-db
        image: mongo:latest
        ports:
        - containerPort: 27017
