kind: Service
apiVersion: v1
metadata:
  name: order-api-service
spec:
  selector:
    app: order-api
  type: NodePort
  ports:
  - name: http-port
    port: 80
    targetPort: 80
  - name: https-port
    port: 443
    targetPort: 443
