kind: Service
apiVersion: v1
metadata:
  name: order-db-service
spec:
  selector:
    app: order-db
  #type: NodePort - uncomment to reach mongo from minikube
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
